### ISSUE TITLE
Can we edit PNG file with included copy of diaram?

### ISSUE THREAD

**Issue by sm-g** [jgraph/drawio-github#2]
I want to commit in `docs/images` only png files to use them in wiki. I need to update them in draw.io editor.

Now only `https://www.draw.io/#Hsm-g%2FREPO%2Fbranch%2FImage.xml` works, when I load `https://www.draw.io/#Hsm-g%2FREPO%2Fbranch%2FImage.png` I got 404 for
`api.github.com/repos/sm-g/REPO/contents/Image.png?ref=branch&token=15d6dc94d3761ec8ac04583e959db54be4f81111`

So I need to store both xml and png, and manually export png after edit.

**Comment by alderg** [comment]
This should work. What browser and version have you tried?

**Comment by sm-g** [comment]
Chrome 59.0.3071.115

**Comment by alderg** [comment]
Can you check in the network tab if there is an error message returned from the server (does the file exist)? I've just checked with Chrome 59 and opening a PNG from a repo works for me (saving isn't possible using the webapp). For saving the PNG with XML, you could use draw.io Desktop (but I think they made it impossible to install it on anything other than Chromebooks).

**Comment by sm-g** [comment]
I got 404 for `api.github.com/repos/sm-g/REPO/contents/Image.png?ref=branch&token=15d6dc94d3761ec8ac04583e959db54be4f81111`. Xml file in same locations opens

**Comment by alderg** [comment]
404 means the file does not exist.

**Comment by sm-g** [comment]
It _does_ exist, "Select File" dialog allows to click on it. But url it is generate (same as for xml but with token) is 404 url. On github png files can be downloaded from url containing "raw": https://github.com/sm-g/REPO/raw/BRANCH/Image.png.

**Comment by alderg** [comment]
This link does not work for me.

**Comment by sm-g** [comment]
you can find sample in this repo, https://raw.githubusercontent.com/jgraph/drawio-github/master/diagram.png

**Comment by alderg** [comment]
I can open https://raw.githubusercontent.com/jgraph/drawio-github/master/diagram.png

**Comment by sm-g** [comment]
Well, issue for now is not "PNG file with included copy of diaram not editable", but "Select file dialog generates wrong url for png files".

**Comment by alderg** [comment]
Well, what I know so far is:
- The URL looks correct.
- The RAW link produces a 404 error.
- We can't reproduce this error.

**Comment by sm-g** [comment]
Yes, I'm working with private repo

**Comment by alderg** [comment]
We're unable to reproduce this. Could you create a private repo with a PNG that fails and give me access, please?

**Comment by sm-g** [comment]
"In order to make this repository private, you’ll need to upgrade your account. 
This will cost $7/month and you'll get unlimited private repositories. You can cancel anytime."

seems I cannot

**Comment by alderg** [comment]
Can you reproduce this with a public repo?

**Comment by sm-g** [comment]
I created public repo, "Select file" opens same url (https://api.github.com/repos/sm-g/pqwerpoiuqewpriulkj/contents/Untitled%20Diagram.png?ref=master&token=12d6150452f772180c1a60a067eb3badf78892c4) and now it is returning some json. I guess you just use `download_url` from it? It can be generated by draw.io for private repos.

**Comment by alderg** [comment]
download_url is only used for File, Publish, Link.

**Comment by alderg** [comment]
Another solution is to use the Chrome App at https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla and edit the files in a a local clone of the repo (works for the wiki, too). The Chrome app can edit .png files with embedded XML.
